export type City = {
  id: string;
  nameEn: string;
  nameFa: string;
};


const cities: City[] = [
  { id: "Tehran", nameEn: "Tehran", nameFa: "تهران" },
  { id: "Mashhad", nameEn: "Mashhad", nameFa: "مشهد" },
  { id: "Isfahan", nameEn: "Isfahan", nameFa: "اصفهان" },
  { id: "Karaj", nameEn: "Karaj", nameFa: "کرج" },
  { id: "Shiraz", nameEn: "Shiraz", nameFa: "شیراز" },
  { id: "Tabriz", nameEn: "Tabriz", nameFa: "تبریز" },
  { id: "Qom", nameEn: "Qom", nameFa: "قم" },
  { id: "Ahvaz", nameEn: "Ahvaz", nameFa: "اهواز" },
  { id: "Kermanshah", nameEn: "Kermanshah", nameFa: "کرمانشاه" },
  { id: "Urmia", nameEn: "Urmia", nameFa: "ارومیه" },
  { id: "Rasht", nameEn: "Rasht", nameFa: "رشت" },
  { id: "Zahedan", nameEn: "Zahedan", nameFa: "زاهدان" },
  { id: "Hamadan", nameEn: "Hamadan", nameFa: "همدان" },
  { id: "Kerman", nameEn: "Kerman", nameFa: "کرمان" },
  { id: "Yazd", nameEn: "Yazd", nameFa: "یزد" },
  { id: "Arak", nameEn: "Arak", nameFa: "اراک" },
  { id: "Bandar Abbas", nameEn: "Bandar Abbas", nameFa: "بندرعباس" },
  { id: "Sanandaj", nameEn: "Sanandaj", nameFa: "سنندج" },
  { id: "Zanjan", nameEn: "Zanjan", nameFa: "زنجان" },
  { id: "Sari", nameEn: "Sari", nameFa: "ساری" },
  { id: "Gorgan", nameEn: "Gorgan", nameFa: "گرگان" },
  { id: "Khorramabad", nameEn: "Khorramabad", nameFa: "خرم‌آباد" },
  { id: "Bojnord", nameEn: "Bojnord", nameFa: "بجنورد" },
  { id: "Dezful", nameEn: "Dezful", nameFa: "دزفول" },
  { id: "Sabzevar", nameEn: "Sabzevar", nameFa: "سبزوار" },
  { id: "Behbahan", nameEn: "Behbahan", nameFa: "بهبهان" },
  { id: "Khoy", nameEn: "Khoy", nameFa: "خوی" },
  { id: "Najafabad", nameEn: "Najafabad", nameFa: "نجف‌آباد" },
  { id: "Borujerd", nameEn: "Borujerd", nameFa: "بروجرد" },
  { id: "Qazvin", nameEn: "Qazvin", nameFa: "قزوین" },
  { id: "Bushehr", nameEn: "Bushehr", nameFa: "بوشهر" },
  { id: "Gonbad-e Kavus", nameEn: "Gonbad-e Kavus", nameFa: "گنبد کاووس" },
  { id: "Neyshabur", nameEn: "Neyshabur", nameFa: "نیشابور" },
  { id: "Kashan", nameEn: "Kashan", nameFa: "کاشان" },
  { id: "Quchan", nameEn: "Quchan", nameFa: "قوچان" },
  { id: "Zabol", nameEn: "Zabol", nameFa: "زابل" },
  { id: "Semnan", nameEn: "Semnan", nameFa: "سمنان" },
  { id: "Torbat-e Heydariyeh", nameEn: "Torbat-e Heydariyeh", nameFa: "تربت حیدریه" },
  { id: "Shahrekord", nameEn: "Shahrekord", nameFa: "شهرکرد" },
  { id: "Khaf", nameEn: "Khaf", nameFa: "خواف" },
  { id: "Iran-Shahr", nameEn: "Iran-Shahr", nameFa: "ایرانشهر" },
  { id: "London", nameEn: "London", nameFa: "لندن" },
  { id: "Paris", nameEn: "Paris", nameFa: "پاریس" },
  { id: "New York", nameEn: "New York", nameFa: "نیویورک" },
  { id: "Tokyo", nameEn: "Tokyo", nameFa: "توکیو" },
  { id: "Berlin", nameEn: "Berlin", nameFa: "برلین" },
  { id: "Madrid", nameEn: "Madrid", nameFa: "مادرید" },
  { id: "Rome", nameEn: "Rome", nameFa: "رم" },
  { id: "Beijing", nameEn: "Beijing", nameFa: "پکن" },
  { id: "Dubai", nameEn: "Dubai", nameFa: "دبی" },
  { id: "Istanbul", nameEn: "Istanbul", nameFa: "استانبول" },
  { id: "Moscow", nameEn: "Moscow", nameFa: "مسکو" },
  { id: "Cairo", nameEn: "Cairo", nameFa: "قاهره" },
  { id: "Bangkok", nameEn: "Bangkok", nameFa: "بانکوک" },
  { id: "Seoul", nameEn: "Seoul", nameFa: "سئول" },
  { id: "Kabul", nameEn: "Kabul", nameFa: "کابل" },
  { id: "Baghdad", nameEn: "Baghdad", nameFa: "بغداد" },
  { id: "Karachi", nameEn: "Karachi", nameFa: "کراچی" },
  { id: "Delhi", nameEn: "Delhi", nameFa: "دهلی" },
  { id: "Lahore", nameEn: "Lahore", nameFa: "لاهور" },
  { id: "Singapore", nameEn: "Singapore", nameFa: "سنگاپور" },
  { id: "Sydney", nameEn: "Sydney", nameFa: "سیدنی" },
  { id: "Toronto", nameEn: "Toronto", nameFa: "تورنتو" },
  { id: "Chicago", nameEn: "Chicago", nameFa: "شیکاگو" },
  { id: "Los Angeles", nameEn: "Los Angeles", nameFa: "لس‌آنجلس" },
];

export default cities;
